package view;

import java.awt.Color;
import java.rmi.Naming;
import javax.swing.JOptionPane;
import principal.StubInterface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jaiminho
 */
public class ClienteDialog extends javax.swing.JDialog {

    /**
     * Creates new form ClienteDialog
     */
    public ClienteDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComando = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSeta = new javax.swing.JButton();
        listarBD = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Integração de Sistemas - III Unidade");
        setBackground(new java.awt.Color(0, 204, 204));
        setBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setResizable(false);

        btnComando.setText("Finalizar um processo via CMD");
        btnComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComandoActionPerformed(evt);
            }
        });

        btnListar.setText("Mostrar Dados do Servidor");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("APLICAÇÃO RMI");

        btnSeta.setText("Aumentar tela desta Aplicação");
        btnSeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetaActionPerformed(evt);
            }
        });

        listarBD.setText("Listar dados de tabela do Banco");
        listarBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBDActionPerformed(evt);
            }
        });

        updateBtn.setText("Atualizar Nome da bandeira (BD)");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSeta, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(btnComando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listarBD, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComando, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listarBD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComandoActionPerformed
        btnListar.setBackground(null);
        listarBD.setBackground(null);
        btnComando.setBackground(Color.green);
        String aplicativo = JOptionPane.showInputDialog("Digite o aplicativo a ser finalizado:");

        if (aplicativo != null) {

            try {
                StubInterface c = (StubInterface) Naming.lookup("rmi://localhost:1099/AppService");
                JOptionPane.showMessageDialog(null, c.prompt(aplicativo));

            } catch (Exception e) {
                System.out.println("Erro " + e);
            }
        } else {
            aplicativo = "cmd";
        }

    }//GEN-LAST:event_btnComandoActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        btnComando.setBackground(null);
        listarBD.setBackground(null);
        btnListar.setBackground(Color.green);
        try {
            StubInterface c = (StubInterface) Naming.lookup("rmi://localhost:1099/AppService");
            JOptionPane.showMessageDialog(null, c.dadosServer());

        } catch (Exception e) {
            System.out.println("Erro " + e);
        }
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnSetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetaActionPerformed
        btnListar.setBackground(null);
        btnComando.setBackground(null);
        listarBD.setBackground(null);
        try {
            StubInterface c = (StubInterface) Naming.lookup("rmi://localhost:1099/AppService");
            this.setBounds(c.interManip(this.getX()), c.interManip(this.getY() - 50), this.getWidth(), c.interManip(this.getHeight()));

        } catch (Exception e) {
            System.out.println("Erro " + e);
        }
    }//GEN-LAST:event_btnSetaActionPerformed

    private void listarBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBDActionPerformed
        btnListar.setBackground(null);
        btnComando.setBackground(null);
        listarBD.setBackground(Color.green);
        try {
            StubInterface c = (StubInterface) Naming.lookup("rmi://localhost:1099/AppService");
            JOptionPane.showMessageDialog(null, c.dadosBD());
        } catch (Exception e) {
            System.out.println("Erro " + e);
        }
    }//GEN-LAST:event_listarBDActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            StubInterface c = (StubInterface) Naming.lookup("rmi://localhost:1099/AppService");
            c.update();
        } catch (Exception e) {
            System.out.println("Erro " + e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed
    /**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClienteDialog dialog = new ClienteDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComando;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnSeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listarBD;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
